# Built from template located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml

default:
    cache:
        paths:
            - .cache/pip

    before_script:
        - apt-get update -yq && apt-get install -yq curl
        - python --version    # For debugging.

.unittest:
    stage: test
    variables:
        # Change pip's cache directory to be inside the project directory.
        PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

    script:
        - python -m pip install psutil
        - python -m unittest --verbose --failfast

py38:
    image: python:3.8
    extends: .unittest

py39:
    image: python:3.9
    extends: .unittest

py310:
    image: python:3.10
    extends: .unittest
